### PR TITLE
Removed dependency on static fields like databaseMapper, ...

### LINKED ISSUE #25: Creating an IDatabase from service provider throws exception if fluent configuration is used
## Library name and version
- Kros.KORM.Extensions.Asp 1.1.0-alfa

## Description

If KORM is added with fluent database configuration, it throws an exception when trying to get `IDatabase` from service provider.

## Steps To Reproduce
1. Create a database configuration using fluent API:

``` csharp
public class DatabaseConfiguration : DatabaseConfigurationBase
{
    public override void OnModelCreating(ModelConfigurationBuilder modelBuilder)
    {
        modelBuilder.Entity<Invoice>()
            .HasTableName("Invoices")
            .UseConverterForProperties<string>(NullAndTrimStringConverter.ConvertNullAndTrimString)
    }
}
```

2. Use this configuration when adding KORM to service provider:

``` csharp
public override void ConfigureServices(IServiceCollection services)
{
    services.AddKorm(configuration).UseDatabaseConfiguration<DatabaseConfiguration>();
}
```

3. Try to use `IDatabase` (just inject it in some controller). Application throws when accessing that controller.

## Additional info

The bug is in [KormBuilder](https://github.com/Kros-sk/Kros.KORM.Extensions.Asp/blob/master/src/KormBuilder.cs) class. The problem is, that [KORM is added as scoped](https://github.com/Kros-sk/Kros.KORM.Extensions.Asp/blob/master/src/ServiceCollectionExtensions.cs#L87) to the container (which is good), but every time an instance is asked for, [it is being built again](https://github.com/Kros-sk/Kros.KORM.Extensions.Asp/blob/master/src/ServiceCollectionExtensions.cs#L89). But [`Build()`](https://github.com/Kros-sk/Kros.KORM.Extensions.Asp/blob/master/src/KormBuilder.cs#L158) method is called on the same (global) instance of [`IDatabaseBuilder`](https://github.com/Kros-sk/Kros.KORM.Extensions.Asp/blob/master/src/KormBuilder.cs#L33). This way, fluent configuration API is is called multiple times for the same `ModelConfigurationBuilder` instance. There are couple of checks in fluent config API, that prevents duplicate configuration and these checks throw the exception.

### PR DESCRIPTION
**Pull request by Burgyn**
Closes #25

I removed dependency on static fields like `DatabaseMapper`, ...
Idea of `IDatabaseBuilder`:
- use it to configure things needed to create `IDatabase`
- when everything is configured, the `Build` method is used to create an `IDatabase` instance.
- The `Build` method can be call multiple times, always creating a new instance of `IDatabase` but with the same configuration.
- Multiple `IDatabase` instances created by one builder instance, share mapping cache, dynamic factories, ...
- ASP.NET Core applications use one instance of builder and call build to inject `IDatabase` into classes ...

### CODE REVIEW

File: src/Database.DatabaseBuilder.cs [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+    public partial class Database
+    {
+        private class DatabaseBuilder : IDatabaseBuilder
+        {
+            private IQueryProviderFactory _queryProviderFactory;
+            private ConnectionStringSettings _connectionString;
+            private DbConnection _connection;
+            private IModelFactory _modelFactory;
+            private DatabaseConfigurationBase _databaseConfiguration;
+            private Lazy<ConventionModelMapper> _conventionModelMapper;
```
Comment (satano) [inline src/Database.DatabaseBuilder.cs]:
```suggestion
            private readonly Lazy<ConventionModelMapper> _conventionModelMapper;
```

File: src/Database.DatabaseBuilder.cs [hunk 2]
```diff
@@ -0,0 +1,183 @@
...
+            private Lazy<DatabaseMapper> _databaseMapper;
```
Comment (satano) [inline src/Database.DatabaseBuilder.cs]:
```suggestion
            private readonly Lazy<DatabaseMapper> _databaseMapper;
```

File: src/Database.DatabaseBuilder.cs [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+            private Lazy<IQueryProvider> _queryProvider;
```
Comment (satano) [inline src/Database.DatabaseBuilder.cs]:
```suggestion
            private readonly Lazy<IQueryProvider> _queryProvider;
```

File: src/Database.DatabaseBuilder.cs [hunk 4]
```diff
@@ -0,0 +1,183 @@
...
+            private Lazy<ModelBuilder> _modelBuilder;
```
Comment (satano) [inline src/Database.DatabaseBuilder.cs]:
```suggestion
            private readonly Lazy<ModelBuilder> _modelBuilder;
```
