### PR TITLE
Fix bug #9

### LINKED ISSUE #9: Sum throws error when there are no data to sumarize
## Library name and version
- Kros.KORM 3.7.2

## Description
Calling _database.Query<Person>().Where(person => person.TermId == termId).Sum(person => person.Count); throws SqlNullValueException: Data is Null when there are no data with required conditions.

## Expected behavior
Sum function should return 0

## Actual behavior
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
SqlNullValueException: Data is Null. This method or property cannot be called on Null values.

**Workaround:** 
_database.Query<Person>().Where(person => person.TermId == termId).**AsEnumerable()**.Sum(person => person.Count);

### PR DESCRIPTION
**Pull request by Burgyn**
Closes #9

### CODE REVIEW

File: src/Materializer/DynamicMethodModelFactory.cs [hunk 1]
```diff
@@ -114,6 +114,11 @@ private static T FactoryForValueType<T>(IDataReader reader)
 
             var valueGetter = GetReaderValueGetter(srcType);
 
+            if (reader.IsDBNull(0))
```
Comment (satano) [inline src/Materializer/DynamicMethodModelFactory.cs]: This condition can be the first statement in the method.
