### PR TITLE
Simple boolean LINQ conditions, delete using variable does not throw NotSupportedException

### LINKED ISSUE #43: NotSupportedException when deleting using LINQ
## Library name and version
- Kros.KORM 4.0-alpha10

## Description
Delete throws NotSupportedException.

## Steps To Reproduce
``` C#
public async Task DeleteDocuments(long c)
{
 IDBSet<Document> dbSet = _database.Query<Document>().AsDbSet();
 dbSet.Delete(x => x.CompanyId == c); //Throws exception. Message: The member 'c' is not supported.
 //dbSet.Delete(x => x.CompanyId == 5); //Works fine.
 await dbSet.CommitChangesAsync();
}
```

### PR DESCRIPTION
**Pull request by satano**
Closes #43 

- Condition for `DbSet.Delete(...)` now works with variables, methods and properties of another object.
- Boolean conditions can be written in simpler way. We can write:
  - `item => item.IsDeleted` instead of `item => item.IsDeleted == true`
  - `item => !item.IsDeleted` instead of `item => item.IsDeleted == false`

### CODE REVIEW

File: src/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 1]
```diff
@@ -291,11 +316,48 @@ public virtual Expression VisitOrderBy(OrderByExpression orderByExpression)
         /// </summary>
         protected StringBuilder LinqStringBuilder { get; private set; }
 
+        /// <summary>
+        /// Adds new parameterto the SQL with specified <paramref name="value"/>.
```
Comment (LukasSefcik) [inline src/Query/Sql/DefaultQuerySqlGenerator.cs]: Just a typo `parameterto`.

File: src/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 2]
```diff
@@ -291,11 +316,48 @@ public virtual Expression VisitOrderBy(OrderByExpression orderByExpression)
...
+
+        private void AppendBooleanCondition(MemberExpression node, bool value, bool negate)
+        {
+            string op = negate ? "<>" : "=";
+            LinqStringBuilder.AppendFormat("({0} {1} {2})", GetColumnNameFromMember(node), op, value ? SqlTrue : SqlFalse);
+        }
+
+        private bool IsBooleanPropertyExpression(Expression node)
+        {
+            if (node is MemberExpression memberExp)
```
Comment (Burgyn) [inline src/Query/Sql/DefaultQuerySqlGenerator.cs]: Why 2 `if` statements?
Why not:
```CSharp
if (node is MemberExpression memberExp && memberExp.Member is PropertyInfo propInfo)
```
