### PR TITLE
WIP Delete by id and condition

### LINKED ISSUE #37: Simpler Delete of entities
Starting discussion about **Simplier `Delete` of entities** from #8.

----

Now, if we want to delete an entity, we can use direct SQL statement (`ExecuteNonQuery`), or `DbSet`. The disadvantage of `ExecuteNonQuery` is, that it does not have ane knowledge about entity type, so the SQL must be hand written. Disadvantage of `DbSet` is that we need to create an instance of the entity, just to have its ID. I'd like to have something which can be used without creating an entity instance:

``` csharp
_database.Delete<EntityType>(123)
```

We could support delete with condition (instead of just primary key):

``` csharp
_database.Delete<EntityType>(item => item.ParentId == 123);
```

Things to think about:
- Where to implement this (`IDbSet`, `IDatabase`...). And it should at least support `int` and `long` primary keys (generic of `<TEntity, TKey>`?), but better any keys (what about composite ones?).
- What kind of expressions to support when deleting with condition and throw some exception if we cannot translate it into SQL.

### ToDo:

- [x] Delete by id
  - [x] Check if id has the same type as primary key property
- [x] Integration test for Delete by id
- [x] Delete by condition
  - [x] Prototype
  - [x] Implementation
  - [x] Unit and integration tests
  - [x] xml comments
- [x] Extension for easy calling `Delete` and `Add` operation.
- [ ] Info to readme file.

### PR DESCRIPTION
**Pull request by Burgyn**
Closes #37 
This PR add support for deleting items by ids and conditions.

----

### `DbSet` has new methods:

```CSharp
void Delete(object id);
void Delete(Expression<Func<TEntity, bool>> condition);
void Delete(string condition, params object[] parameters);
```

- I don't add overload with `IEnumerable ids` because this has colision with `object id`.
- `DbSet` has properties like `AddedItems`, `EditedItems`, `DeletedItems`. I decided not to add property to these new methods. It doesn't make sense to me.

### `IDatabaseExtensions`

I created the new `IDatabaseExtensions` class. This class contains extensions for easier calling methods like `Add`, `Edit`, `Delete`.

```CSharp
await database.AddAsync(person);
await database.DeleteAsync(person);
await database.DeleteAsync<Person>(2);
await database.DeleteAsync<Person>(p=> p.Id == 2);
await database.DeleteAsync<Person>("Id = @1", 2);
await database.EditAsync(person);
await database.EditAsync(person, "Id", "Age");

```

----

When you check this PR I will write the documentation into the readme.

### CODE REVIEW

File: src/Query/Sql/ISqlExpressionVisitor.cs [hunk 1]
```diff
@@ -15,6 +15,8 @@ public interface ISqlExpressionVisitor
         /// <returns>SQL select command text.</returns>
         QueryInfo GenerateSql(Expression expression);
 
+        WhereExpression GenerateWhereCondition(Expression whereExpression);
```
Comment (satano) [inline src/Query/Sql/ISqlExpressionVisitor.cs]: Missing docs.

File: tests/Kros.KORM.UnitTests/Query/Sql/DefaultQuerySqlGeneratorShould.cs [hunk 2]
```diff
@@ -1,9 +1,11 @@
-﻿using FluentAssertions;
+﻿using Castle.DynamicProxy.Generators.Emitters.SimpleAST;
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/Query/Sql/DefaultQuerySqlGeneratorShould.cs]: Unnecessary using.

File: tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs [hunk 3]
```diff
@@ -67,7 +67,7 @@ public void HaveCorrectOneDeleteQuery()
         {
             const string expectedQuery = "DELETE FROM [Foo] WHERE [IdRow] IN (@P1,@P2,@P3,@P4,@P5,@P6,@P7,@P8,@P9,@P10,@P11,@P12,@P13,@P14,@P15)";
 
-            var result = GetFooGenerator().GetDeleteCommands(GetFooList(15)).ToList();
+            var result = GetFooGenerator().GetDeleteCommands(Enumerable.Range(1, 15)).ToList();
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/CommandGenerator/CommandGeneratorShould.cs]: Replaced `GetFooList` method is not used anymore, but still in sources.

File: tests/Kros.KORM.UnitTests/Query/DbSetShould.cs [hunk 4]
```diff
@@ -263,6 +264,51 @@ public void ThrowExceptionWhenProviderDoesNotSupportIdnetity()
...
+            {
+                new ColumnInfo(){
+                    Name = "Id",
+                    IsPrimaryKey = true,
+                    PropertyInfo = typeof(Person).GetProperty(nameof(Person.Id))
+                }
+            }, new List<PropertyInfo>(), null);
+
+            var dbSet = new DbSet<Person>(Substitute.For<ICommandGenerator<Person>>(),
+                                         Substitute.For<IQueryProvider>(),
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/Query/DbSetShould.cs]: Wrong indentation.

File: tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs [hunk 5]
```diff
@@ -12,6 +12,7 @@
 using System.Linq;
 using System.Threading.Tasks;
 using Xunit;
+using Newtonsoft.Json.Linq;
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs]: Unnecessary using (and some of them are not sorted).

File: tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs [hunk 6]
```diff
@@ -297,6 +298,69 @@ public async Task DeleteDataAsync()
...
+            }
+        }
+
+        [Fact]
+        public async Task DeleteDataByLinqConditionAsync()
+        {
+            using (var korm = CreateDatabase(CreateTable_TestTable, InsertDataScript))
+            {
+                var dbSet = korm.Query<Person>().AsDbSet();
+                dbSet.Delete(p=> p.Id == 1);
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs]:
```suggestion
                dbSet.Delete(p => p.Id == 1);
```

File: tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs [hunk 7]
```diff
@@ -297,6 +298,69 @@ public async Task DeleteDataAsync()
...
+                dbSet.Delete(2);
+
+                await dbSet.CommitChangesAsync();
+
+                korm.Query<Person>().Should().BeEmpty();
+            }
+        }
+
+        [Fact]
+        public async Task DeleteDataByLinqConditionAsync()
```
Comment (satano) [inline tests/Kros.KORM.UnitTests/Integration/DbSetShould.cs]: Can we add test to delete by non-primary key column (`p.ParentId == 42`)? Maybe condition with more than one column (`p.Value > 10 && p.Value < 20`)?

File: src/IDatabaseExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+    /// </summary>
+    public static class IDatabaseExtensions
+    {
+        /// <summary>
+        /// Adds the <paramref name="entity"/> to the database.
+        /// </summary>
+        /// <typeparam name="TEntity">Entity type.</typeparam>
+        /// <param name="database"><see cref="IDatabase"/> instance.</param>
+        /// <param name="entity">The entity to add.</param>
+        public static async Task AddAsync<TEntity>(this IDatabase database, TEntity entity) where TEntity : class
```
Comment (satano) [inline src/IDatabaseExtensions.cs]: How all this works with transactions?

Comment (Burgyn) [reply src/IDatabaseExtensions.cs]: Very well :-) . By default, as with `DbSet`, the call is wrapped in an implicit transaction. Of course, it is possible to explicitly call `database.BeginTransacion()` and wrap multiple calls in one transaction.
